# Generated by Django 3.1 on 2020-08-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'Aktualność', 'verbose_name_plural': 'Aktualności'},
        ),
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='posts.image'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
