# Generated by Django 3.1 on 2020-08-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
