# Generated by Django 3.1 on 2020-08-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200815_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='opublikowany',
            new_name='public',
        ),
    ]
