# Generated by Django 3.1 on 2020-08-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200815_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Treść',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Opublikuj',
            new_name='public',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Tytuł',
            new_name='title',
        ),
    ]
