# Generated by Django 3.1 on 2020-09-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200831_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenews',
            name='file',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
